import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nicolas Palacio",
  description: "Portfolio generated by Next.js",
  icons: {
    icon: "/fotoperfilsinfondo.ico", // ruta del icono
    shortcut: "/fotoperfilsinfondo.ico", // (opcional) icono de acceso directo
    apple: "//fotoperfilsinfondo.ico", // (opcional) icono de Apple Touch
  },
  openGraph: {
    title: "Nicolas Palacio - Portfolio",
    description: "Desarrollador Frontend apasionado por la creación de aplicaciones web.",
    url: "https://nicojpalacio.vercel.app/", // Cambia esto por tu URL
    images: [
      {
        url: "/fotoperfilsinfondo.ico", // La ruta a la imagen de la miniatura
        width: 800,
        height: 600,
        alt: "Nicolas Palacio - Portfolio",
      },
    ],
    siteName: "Nicolas Palacio",
  },
  twitter: {
    card: "summary_large_image",
    title: "Nicolas Palacio - Portfolio",
    description: "Desarrollador Frontend apasionado por la creación de aplicaciones web.",
    images: ["/fotoperfilsinfondo.ico"], // La misma imagen para Twitter
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
