import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nicolas Palacio",
  description: "Portfolio generated by Next.js",
  icons: {
    icon: "/fotoperfilsinfondo.ico", // ruta del icono
    shortcut: "/fotoperfilsinfondo.ico", // (opcional) icono de acceso directo
    apple: "//fotoperfilsinfondo.ico", // (opcional) icono de Apple Touch
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
